### PR TITLE
LRQA-77407 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-77407

Tested here: https://github.com/Kvale1733/liferay-portal/pull/203

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@kyle-miho This is what Victor and I decided on for the startup suite. We actually didn't need to measure the startup time. Just needed to startup several times to check if startup passes. We picked some stable Web Content tests for this. Couldn't really figure out a way not to run any tests.

**Comment by kyle-miho** [comment]
ci:test:forward

**Comment by kyle-miho** [comment]
tests looks good, just making sure it doesnt break stable

**Comment by kyle-miho** [comment]
ci:forward

**Pull request closed without merging**
