### PR TITLE
LRQA-75853, LRQA-75854, LRQA-75855, LRQA-75856, LRQA-75857, LRQA-75858, LRQA-75859, LRQA-75860 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-75853
https://issues.liferay.com/browse/LRQA-75854
https://issues.liferay.com/browse/LRQA-75855
https://issues.liferay.com/browse/LRQA-75856
https://issues.liferay.com/browse/LRQA-75857
https://issues.liferay.com/browse/LRQA-75858
https://issues.liferay.com/browse/LRQA-75859
https://issues.liferay.com/browse/LRQA-75860

Tested here: https://github.com/Kvale1733/liferay-portal/pull/149

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
See comments and resend, thanks!

**Comment by Kvale1733** [comment]
@kyle-miho  I don't see any comments

**Comment by kyle-miho** [comment]
@Kvale1733 should be visible now i had to complete the review

**Pull request closed without merging**
