### PR TITLE
LPS-90273 Build lang

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/149. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/c5e864749741~1...c5e864749741) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
