### PR TITLE
master-qa-49565

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-49565

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Pull request closed without merging**
