### PR TITLE
LRQA-73302 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-73302

Tested here: https://github.com/Kvale1733/liferay-portal/pull/186

### CODE REVIEW

**Comment by Kvale1733** [comment]
@kyle-miho So this is the FACES PR again. All tests pass now. In updating the repos I found this bug: https://issues.liferay.com/browse/FACES-3686. It was fixed already but with how the FACES tests work I can't just update the commit to for Bridge-Impl to the fix because the commit before that prepares for another version's development and that causes issues when compiling that repo. The commits for each repo need to be the most recent release commit, which for the Bridge-Impl repo is this one: https://github.com/liferay/liferay-faces-bridge-impl/commit/b3251170b8d6b7b7462c35361dbb9a899f849ee5. So If I want to include any commits after that (the fix for this bug) I need to cherry pick, which is what I did. Once 4.3.1 is done then I can update the git-commit again and remove the cherry pick.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:forward

**Comment by kyle-miho** [comment]
@Kvale1733 Create a Jira ticket to remove the workaround if you have not yet done so, so we dont forget

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
