### PR TITLE
LPS-96689 Fix integration tests

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
@jkappler @ruben-pulido there seem to be a lot of errors with this pull, im investigating!

**Comment by kyle-miho** [comment]
Fixed 3 integration tests, looking at other 2 now

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/533. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/f98a00f98b8a~1...f98a00f98b8a)

**Pull request closed without merging**
