### PR TITLE
LPS-96228 Increase coverage of Fragment Entry Service Integration Tests

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/496. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/faf9da331b67~11...faf9da331b67) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
