### PR TITLE
LPS-131823 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-131823

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:lpkg

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:test:license

**Comment by kyle-miho** [comment]
@vicnate5 2 license failures, 1 is failing at head, 1 is portal smoke failing (seems to be unique) im not sure if its because it was being obscured before, or if this actually caused it to fail

**Comment by vicnate5** [comment]
@kyle-miho Failures don't look related, most of the tests passing is good.

**Pull request closed without merging**
