### PR TITLE
LRQA-79897 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-79897

@kyle-miho Tested here: https://github.com/Kvale1733/liferay-portal/pull/318

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@vicnate5 This one is ready for review.

**Comment by vicnate5** [comment]
@Kvale1733 Just one change needed.

I see  this code repeated a lot in this testcase file, can you move to a macro? Only the `newFileContent` is unique.

```
			var tomcatBinDir = PropsUtil.get("app.server.bin.dir");

			var setenvFile = "${tomcatBinDir}/setenv.sh";

			var fileContent = FileUtil.read(${setenvFile});
			var companyId = JSONCompany.getCompanyId();

			var newFileContent = '''${fileContent}
export LIFERAY_PROPS_BY_COMPANY_${companyId}=default.regular.theme.id=minium_WAR_miniumtheme
''';

			FileUtil.write(${setenvFile}, ${newFileContent});
			```

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
