### PR TITLE
LRQA-76293 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
[LRQA-76293](https://issues.liferay.com/browse/LRQA-76293)

Tested here:https://github.com/Kvale1733/liferay-portal/pull/184

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@kyle-miho This PR fixes the weblogic issue with upgrade tests.

**Comment by kyle-miho** [comment]
isn't this already pushed upstream? https://github.com/kyle-miho/liferay-portal/commit/592273d0c55f9fddb41e1e615a176aba3a7133bb

**Comment by kyle-miho** [comment]
im closing this as duplicate

**Pull request closed without merging**
