### PR TITLE
LPS-100615 Compare body element contents to avoid header differences in CI

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Hey @kyle-miho, I really don't know what it happening with this test in CI because locally it works as expected. If you have any thoughts feel free to check. I'll give it another try tomorrow.
Thanks!

**Comment by kyle-miho** [comment]
@pavel-savinov ill look at it later today when i have time

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/231. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/3765b4ea7d4f~1...3765b4ea7d4f)

**Pull request closed without merging**
