### PR TITLE
Lrqa 55106

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@kyle-miho test out this version, I was not able to see any failure with this. if you get to see any, paste me the error stack.

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
@shuyangzhou got this error when starting up a second time (possibly a race condition, possibly only occurs on second startup)
https://gist.github.com/kyle-miho/e0d29fb52652da6e6a5ef18f6c51d2f2

Also got this on shutdown (likely a race condition with the order on how the modules deactivate)
https://gist.github.com/kyle-miho/133e0230194354222c242e9e0f0abfc7

**Comment by vicnate5** [comment]
@shuyangzhou @kyle-miho can this be revisited soon? test flakiness due to the UI instance setup/teardown in is becoming a bigger issue with ci:forward.

**Pull request closed without merging**
