### PR TITLE
LPS-92248 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-92248
cc: @jkappler @JorgeFerrer @brianchiu

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
fyi some weird bug happened, and there is an invisible commit for renaming Standard Pages back to Content Pages

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
