### PR TITLE
LRQA-80656 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-80656

Resent from https://github.com/kyle-miho/liferay-portal/pull/861 with rebase

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:forward

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
already merged, closing

**Pull request closed without merging**
