### PR TITLE
LPS-102820 Rename to reflect the meaning because LayoutTemplate is a different entity

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hey @kyle-miho, this pull breaks some POSHI tests for sure. Could you please take a look and move the tests or ignore them for a moment?

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79358. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/8631f1597509~2...8631f1597509)

**Pull request closed without merging**
