### PR TITLE
Enable sqlserver 2017 batches.

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-58306

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:upgrade

**Comment by koor4356** [comment]
Missing "import-database.sh: no such file or directory." It is not implemented.
`rebuild-legacy-database:
    [unzip] Expanding: /opt/dev/projects/github/liferay-qa-portal-legacy-ee/7.2.10/data-archive/data-archive-portal-sqlserver.zip into /opt/dev/projects/github/liferay-portal/bundles
     [exec] lstat /opt/dev/projects/github/liferay-portal/import-database.sh: no such file or directory
[stopwatch] [run.batch.test.action: 50.650 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:361: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1533: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1537: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12601: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:11582: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:528: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:647: exec returned: 1
      [get] Getting: http://test-1-6/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/418053//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20200803113153461.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20200803113153461.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null29865017.properties
`

**Comment by kyle-miho** [comment]
Hey @koor4356 is this missing a DB import Dump? or does it seem like the ant macro does not work? If the ant macro does not work for upgrades we could ask for help from the LRCI team with a LRCI ticket, if its the DB import dump, then we need to create a task to generate the dump (but i think we should have dumps already for sql server 2017)

**Comment by koor4356** [comment]
@kyle-miho sql server is not supported in 6.2+ according to victor. So we do not have sqlserver database dump for 6.2+, they are expected to fail. We have sqlserver database dump for 7.0+, 7.1+, and 7.2+ for portal upgrade smoke tests only. The issue is that sqlserver import is not implemented. Search for "import-database.sh" in build-test.xml and see implementation for the others database.

**Comment by koor4356** [comment]
ci:test:upgrade

**Comment by koor4356** [comment]
@kyle-miho I have added restore sql server database and trigger the ci again. This works, portal grade smoke tests should be passing or fail for different reason. Yes, we limit sql server to run 7.0+, 7.1+, and 7.2+ only.

**Comment by kyle-miho** [comment]
Hey @koor4356 the Post Upgrade tests need to be adjusted, for example
     [echo] LocalFile.OrganizationUpgradeTestCase.testAddOrganizationAfterUpgrade621015.portal.version=6.2.10.15
     [echo] LocalFile.OrganizationUpgradeTestCase.testAddOrganizationAfterUpgrade621015.testray.component.names=Users and Organizations
     [echo] LocalFile.OrganizationUpgradeTestCase.testAddOrganizationAfterUpgrade621015.database.types=db2,mariadb,mysql,oracle,postgresql,sqlserver,sybase
     [echo] LocalFile.OrganizationUpgradeTestCase.testAddOrganizationAfterUpgrade621015.portal.release=true
     [echo] LocalFile.OrganizationUpgradeTestCase.testAddOrganizationAfterUpgrade621015.portal.upstream=true
     [echo] LocalFile.OrganizationUpgradeTestCase.testAddOrganizationAfterUpgrade621015.priority=5
     [echo] LocalFile.OrganizationUpgradeTestCase.testAddOrganizationAfterUpgrade621015.custom.properties=organizations.types=organization,location
     [echo] LocalFile.OrganizationUpgradeTestCase.testAddOrganizationAfterUpgrade621015.data.archive.type=data-archive-portal
     [echo] LocalFile.OrganizationUpgradeTestCase.testAddOrganizationAfterUpgrade621015.testray.main.component.name=Upgrades User and System Management

sqlserver shouldnt be a database.type included here, since its not present in 6.2 as we said. If we need to explicitly declare the database types it should be fine, but we should remove sqlserver from all 6.2 datadump post upgrade tests since they shouldnt be running

**Comment by kyle-miho** [comment]
message me if that doesnt make sense

**Comment by koor4356** [comment]
@kyle-miho, I have not add any sql server to any tests.
- I am just enabling sql server batches according to your instruction on the ticket.
- I only generated sql server dump for portal grade smoke tests (core infra).
- For 6.2, we will adjust those upgrade tests.
 
Do you want to remove sql server from other upgrade tests and leave it to their respective team?

**Pull request closed without merging**
