### PR TITLE
LRQA-69066 | master

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-69066

This can be backported to 7.3.x.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:help

**Comment by kyle-miho** [comment]
ci:test:license-cluster

**Comment by kyle-miho** [comment]
ci:forward

**Pull request closed without merging**
