### PR TITLE
LRQA-55191 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-55191

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:poshi:nocompile

**Comment by vicnate5** [comment]
@kyle-miho lots of failures with `java.lang.Exception: Invalid addGuestPermissions: 'true' specified. Allowed values are 'true' or 'false'.`

**Comment by kyle-miho** [comment]
ci:test:poshi

**Comment by kyle-miho** [comment]
ci:test:poshi:nocompile

**Comment by kyle-miho** [comment]
ci:test:poshi:nocompile

**Comment by kyle-miho** [comment]
ci:test:poshi

**Comment by kyle-miho** [comment]
ci:test:poshi

**Pull request closed without merging**
