### PR TITLE
LRQA-73302 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-73302

Tested here:https://github.com/Kvale1733/liferay-portal/pull/185

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@Kvale1733 why do we have to cherry pick the fix? Can you explain it to me

**Comment by Kvale1733** [comment]
@kyle-miho Well the way I understood if looks like the faces tests are static in that the the tests run on a specific commit from the four FACES repos. Seems like Victor used the cherry pick method in build-test-jsf.xml while when there was no release branch available. I think I could also change the commit in the bridges-impl git-commit file if that would be better. I'll test if that works right now.

**Comment by Kvale1733** [comment]
@kyle-miho I'm going to figure out a better fix so we don't have to cherry pick anything. Closing this PR.

**Pull request closed without merging**
