### PR TITLE
LPS-131433 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-131433

This is only for master.

@kyle-miho

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:bundle

**Comment by kyle-miho** [comment]
@Tim-Cao ill look at this tmr, ill need to forward to one of our devs after

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
> @Tim-Cao ill look at this tmr, ill need to forward to one of our devs after

Please use the latest bundle, I fixed a buildService issue.

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
