### PR TITLE
Enable sqlserver 2017 batches

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-58306

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:upgrade:nocompile

**Comment by kyle-miho** [comment]
ci:forward

**Comment by kyle-miho** [comment]
ci:forward

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/92663.

**Pull request closed without merging**
