### PR TITLE
LRQA-80990 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-80990

Tested here: https://github.com/Kvale1733/liferay-portal/pull/361

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
FYI this test is currently failing upstream due to an additional issue with the IT account. we should probably also disable the test for now.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:forward

**Pull request closed without merging**
