### PR TITLE
LRQA-78211 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-78211

Tested here: https://github.com/Kvale1733/liferay-portal/pull/215

### CODE REVIEW

**Comment by Kvale1733** [comment]
@kyle-miho The last five tests are ignore for now as they fail due to [LPS-167572](https://issues.liferay.com/browse/LPS-167572)

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@Kvale1733 can you fix the conflicts and resend? I updated my origin as well to make this easier to read

**Comment by kyle-miho** [comment]
Also move the Tests to a file called OSGiConfig.testcase (Also categorized under file install component), same reason as the other PR I reviewed

**Pull request closed without merging**
