### PR TITLE
Enable sqlserver 2017 batches

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-58306

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:upgrade:nocompile

**Comment by koor4356** [comment]
ci:test:upgrade:nocompile

**Comment by kyle-miho** [comment]
ci:foward

**Comment by kyle-miho** [comment]
The semantic versioning issue is already reported, plus any failures revealed from adding this batch should be uncaused by this change

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/385.

**Pull request closed without merging**
