### PR TITLE
LRQA-79756 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-79756

@kyle-miho 
Tested here: https://github.com/Kvale1733/liferay-portal/pull/298

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@Kvale1733 since this touches a json macro that could affect other tests, we should test a wider scope to check this doesnt affect other tests

**Comment by kyle-miho** [comment]
ci:test:acceptance-functional

**Comment by Kvale1733** [comment]
@kyle-miho No regressions caused by the change.

**Comment by kyle-miho** [comment]
ci:forward

**Pull request closed without merging**
