### PR TITLE
LPS-98376 Update tests

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76126. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/d169d6a16644~2...d169d6a16644)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76128. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/abf983c4b788~2...abf983c4b788)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/546. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/abf983c4b788~2...abf983c4b788)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76154. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/abf983c4b788~2...abf983c4b788)

**Pull request closed without merging**
