### PR TITLE
LPS-90273 Update Poshi tests with new names

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
ci:test

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/152. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/153. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/a64304013492~1...a64304013492) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68652. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/0203dbea698f~1...0203dbea698f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
