### PR TITLE
LRQA-79710 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-79710

@kyle-miho Tested relevant here: https://github.com/Kvale1733/liferay-portal/pull/296

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:forward

**Comment by Kvale1733** [comment]
ci:forward

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
