### PR TITLE
LRQA-79883 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-79883

@kyle-miho Tested here:https://github.com/Kvale1733/liferay-portal/pull/316

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@Kvale1733 Test real quick if you can replace the *.class compiled java classes with *.java classes (I wanna say this might work since Poshi should be re-packaging it, not sure if it compiles it, some other examples such as below can include java files). If not its not the end of the world, everything else is good and can forward as is if so

https://github.com/liferay/liferay-portal/tree/master/portal-web/test/functional/com/liferay/portalweb/dependencies/test-app-portlet-7.2.0.war

**Comment by Kvale1733** [comment]
@Kvale1733 Doesn't seem to work. An error appears that the Test1 and Test2 classes were not found. In the example you added the files in the /classes directories are also .class files.

**Comment by kyle-miho** [comment]
@Kvale1733 Does it work if you just add the src directory over? Ideally we can have the code attached so we can make any changes to it if we need to, esp if this module ever breaks in the future. (It doesnt matter if it uses the src code or not, as long as we have visibility over it, as we can at least manually copy it and update the compiled classes after)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
