### PR TITLE
LRQA-81134 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://liferay.atlassian.net/browse/LRQA-81134

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@Kvale1733 I don't really like this solution since it seems like we are just avoiding a bug, but since we arent testing ExportImport with this test mainly, but Azure Store functionality, this should be fine for now, I asked around on Slack to confirm though

**Comment by kyle-miho** [comment]
ci:forward

**Pull request closed without merging**
