### PR TITLE
LPS-85711 Select correct frames when adding content pages

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @kyle-miho,

I fixed the bug with the Global Templates, it was not intentionally, thanks!

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@pavel-savinov portal is pretty unstable now, hard to get good results, sorry that this is taking so long, I just don't want to risk bugs getting in if we can help it.

**Comment by kyle-miho** [comment]
@pavel-savinov There is still an issue with Global Page Templates unfortunately. Although it now correctly redirects the user to the Page Configuration area, I think we are creating a "Widget" page instead of the "global page template page", because certain configurations are changed.

For example, check the screenshot here: https://testray.liferay.com/reports/production/logs/test-1-17/1538682030976/test-portal-acceptance-pullrequest(master)/2916/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.Search_SearchGlobalTemplateSmoke/index.html.gz

and you can notice if you check current upstream that Global Page Templates look differently in the config (layout type shouldn't be selectable, inherit changes is no longer present, etc).

**Pull request closed without merging**
