### PR TITLE
LPS-79390 also apply to the new query

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
Hi @kyle-miho, wanted to test this PR and see that it doesn't causes any issues

**Comment by jkappler** [comment]
Hi @kyle-miho, @jpince. I don't know if the error are because of the changes in the PR (it seems that that isn't the case).

Would you please let me know if it's safe to send to Brian? Test pass in local, but you never know.

Thanks! And let me know what you think

**Comment by kyle-miho** [comment]
@jkappler This PR should be safe to send to Brian! Tests look good.

**Comment by kyle-miho** [comment]
'Pull <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pushed to BChan https://github.com/brianchandotcom/liferay-portal/pull/57147 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
@jkappler I am going to manually test this pull locally, (will let you know results soon) to make sure there are no regressions as Brian was concerned about with removing the select DISTINCT query (probably has to do with have duplicate webcontent being loaded), but your change in GROUP BY seems to take that into account, but we can never be too sure.

**Comment by jkappler** [comment]
Thanks @kyle-miho!!!

**Comment by kyle-miho** [comment]
@jkappler Didn't have time to get to this today, will work on this Monday, but could you fix your format to the one BChan specified when you can also? Thanks!

**Pull request closed without merging**
