### PR TITLE
master-qa-49704

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-49704

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
@Tim-Cao the purpose of this ticket is to apply JSONUser.tearDownNonAdminUsers() in order to help cleanup tests. The test you added is outside the scope of this ticket. Also, there is no point into testing that the functionality of a JSON command works since the service should be tested in the integration layer, there are some tests to make sure that the commands correctly execute though, see JSON*Test.macro and JSONSmoke.testcase.

**Pull request closed without merging**
