### PR TITLE
LRQA-75853, LRQA-75854, LRQA-75855, LRQA-75856, LRQA-75857, LRQA-75858, LRQA-75859, LRQA-75860 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-75853
https://issues.liferay.com/browse/LRQA-75854
https://issues.liferay.com/browse/LRQA-75855
https://issues.liferay.com/browse/LRQA-75856
https://issues.liferay.com/browse/LRQA-75857
https://issues.liferay.com/browse/LRQA-75858
https://issues.liferay.com/browse/LRQA-75859
https://issues.liferay.com/browse/LRQA-75860

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@Kvale1733 can you rebase and resend, theres merge conflicts in this pr

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@kyle-miho It's rebased now

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
