### PR TITLE
LRQA-79873 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-79873

Tested here: https://github.com/Kvale1733/liferay-portal/pull/346

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:forward

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
See: https://github.com/brianchandotcom/liferay-portal/pull/137209

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
