### PR TITLE
LPS-78661 Use lang merger where ADTs are used

### PR DESCRIPTION
**Pull request by jkappler**
Hey @kyle-miho, another try at untranslated keys. Same approach as the one from @pavel-savinov (lang merger), but with a small change in Template Handler

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Hey @jkappler It looks like your fix caused some Forms regressions. I'm not too sure of what is exactly happening, it might be helpful to contact Victor or another Forms team member for more information.

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@kyle-miho, just checking again

**Pull request closed without merging**
