### PR TITLE
LPS-92024 When upgrade 7.0 to master, "LayoutPageTemplateEntryNameException" WARN message is thrown during startup

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/402. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/40900fd4c4dd~1...40900fd4c4dd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
