### PR TITLE
Rename Gogo Shell Client

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-54678

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
ci:retest

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82554.

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Pull request closed without merging**
