### PR TITLE
LPS-96689 Adapt configuration in tests to cope with new validation rules

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ruben-pulido, @ealonso

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75902.

**Pull request closed without merging**
