### PR TITLE
LPS-92248 Build lang in asset-publisher-web

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
cc:// @ealonso, @JorgeFerrer

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/166. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70315. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
