### PR TITLE
master-qa-51884

### PR DESCRIPTION
**Pull request by zhangyan0701**
This is the sql.legacy.zip property only. The test case uses it only need to apply to 7.2.x at the moment.
See [kyle-miho/liferay-portal-ee#16](https://github.com/kyle-miho/liferay-portal-ee/pull/16).

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82573.

**Pull request closed without merging**
