### PR TITLE
LPS-92248 Remove markup from the language key

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/163. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/89a6b65510c6~2...89a6b65510c6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/164. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/89a6b65510c6~2...89a6b65510c6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@jkappler @JorgeFerrer see changes to pull i fowarded to myself, fixed the sf issues and merge conflict. I removed the commit 0508eea (LPS-92248 Replace old keys in non-default languages (Rename "Display Pages" as "Display Page Templates")) that runs buildLang, and rebased the branch. I reran buildLang after. Fixed the other sf issue that referenced the wrong language key.

**Pull request closed without merging**
