### PR TITLE
LPS-97378 Decode value

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75561. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/cec533a4c6c6~1...cec533a4c6c6)

**Pull request closed without merging**
