### PR TITLE
LRQA-71948

### PR DESCRIPTION
**Pull request by kevhlee**
__Tickets:__
[LPS-139161](https://issues.liferay.com/browse/LPS-139161)
[LRQA-71948](https://issues.liferay.com/browse/LRQA-71948)

__Notes:__
LGTM. Just added a small SF change. In the future, we can update the integration test if need be. If everything looks good to you, feel free to forward these changes.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:forward

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:close

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/112000

**Pull request closed without merging**
