### PR TITLE
LPS-194932 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://liferay.atlassian.net/browse/LPS-194932

Tested here and that config no longer fails in the test: https://testray.liferay.com/home/-/testray/case_results/2420664848?tab=result

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@Kvale1733 Im not sure if you already checked or not, just make sure to confirm if we need the UI before we turn it off, I double checked and found it here https://liferay.atlassian.net/browse/LPS-161850, LXC created this to use for automation, so the UI is un-needed

**Comment by kyle-miho** [comment]
ci:forward:force

**Comment by Kvale1733** [comment]
ci:forward:force

**Pull request closed without merging**
