### PR TITLE
master-qa-49704-a

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-49704

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81524.

**Pull request closed without merging**
