### PR TITLE
LRQA-79891 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-79891

Tested here: https://github.com/Kvale1733/liferay-portal/pull/314

@kyle-miho Resent from https://github.com/kyle-miho/liferay-portal/pull/750. Added assert to check there are no files in Azure for the added group before the import. Then assert there are files after the group import to verify the import worked on Azure. 

Also the first commit fixes a typo from a different test I sent that causes the setup to fail. I already forwarded the typo fix just rebased this PR to include it for testing since it's not merged yet.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:forward

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:forward

**Pull request closed without merging**
