### PR TITLE
LPS-90273 Build lang in portal-impl

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
@kyle-miho, sf will fail because of some language keys. But we can check if other things fail

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/147. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/b47b69853cab~1...b47b69853cab) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
