### PR TITLE
LRQA-57491 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-57491

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@kyle-miho This is creative, but a little messy
```
var newLine= '''
''';

var typeSettings = StringUtil.regexReplaceAll("${typeSettings}","\\r\\n|\\r|\\n","${newLine}");
```

Did you try the built-in Poshi `${line.separator}`?

**Comment by kyle-miho** [comment]
@vicnate5 not really sure where ${line.separator} is supposed to get translated, but it doesnt work. it just gets translated to 'null', the only way to get this to work is to use a non escaped newline which is the variable called newLine

**Comment by vicnate5** [comment]
@kyle-miho This is something Poshi should be able to give us (instead of creating the new line in the poshiscript) can you ask about this in #poshi?

**Comment by kyle-miho** [comment]
@vicnate5 i can mention this in the poshi chat, but this is also causing a bunch of tests to be somewhat flaky, so i would recommend getting this in first to prevent more quarantined tests, especially since poshi releases are often slow

**Comment by vicnate5** [comment]
Yea, we can push this soon, but I will need to explain what we plan to do about this hacky code.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
rebased, a temp commit was still in here

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
resent: https://github.com/vicnate5/liferay-portal/pull/1480
since the commit diff got messed up

**Pull request closed without merging**
