### PR TITLE
master-qa-49705

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-49705

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/298. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/4df7ca597763~4...4df7ca597763)

**Comment by kyle-miho** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81436. [See changes here.](https://github.com/kyle-miho/liferay-portal/compare/4df7ca597763~4...4df7ca597763)

**Pull request closed without merging**
